### ISSUE TITLE
Add an Example to improve usability

### ISSUE THREAD

**Issue by GERZAC1002** [stm32duino/VL6180X#8]
**Is your feature request/improvement related to a problem? Please describe.**

Getting started with this library is quite overwhelming without an example. Does on need VL6180x_On() or Prepare() or begin()?

**Describe the solution you'd like**

A basic Example for getting measurements would greatly improve the usability without having to dig through the class file.

**Describe alternatives you've considered**

I tried looking for examples online and saw that a similar request in issue #4 was closed without a solution.

**Additional context**

This is my code so far that i taped together trying to get a basic distance measurement, it always prints 0 as value:
```
#include <Wire.h>
#include <vl6180x_class.h>

VL6180X distance(&Wire,NULL);
unsigned long  i;
 
void setup() {
  Wire.setSDA(PB11);
  Wire.setSCL(PB10);
  Serial.begin(9600);
  Wire.begin();
  distance.VL6180x_On();
  distance.RangeConfigInterrupt(CONFIG_GPIO_INTERRUPT_DISABLED);
  distance.Prepare();
  distance.RangeStartContinuousMode();
}

void loop() {
  distance.GetDistance(&i);
  Serial.print("Distance: ");
  Serial.println(i);
  delay(1000);
}
```

**Comment by fpistm** [comment]
@cparata 
any update on this, please ?

**Comment by cparata** [comment]
Hello @GERZAC1002 ,
could you give a look at [this example](https://github.com/stm32duino/X-NUCLEO-6180XA1/blob/main/examples/X_NUCLEO_6180XA1_HelloWorld/X_NUCLEO_6180XA1_HelloWorld.ino)? It should show how to use the library. I think that in your example you forgot to call the "InitSensor" function.
Best Regards,
Carlo
